name: HTML Validator

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.html'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.html'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install html-validate
      run: npm install -g html-validate
    
    - name: Validate HTML
      run: html-validate index.html
    
    - name: Summary
      if: always()
      run: echo "HTML validation complete. Check logs for any errors."